"""
Canonical port registry for PROPAURA (Phase G — SQLite -> PostgreSQL cutover).

These are the ONLY port numbers that matter. Every layer derives from here:

  - deploy/ports.env        (bash form, regenerated by deploy.py at run time)
  - compose.dev.yml         (frontend 28001, backend 28002, storage 28003,
                             database 28004, nginx 28005, ngrok dashboard 28006)
  - compose.prod.yml        (backend 28011, storage 28012, database 28013,
                             nginx 28014, ngrok dashboard 28015)
  - nginx listen/upstreams  (dev: gateway listen 28005 -> frontend 28001 /
                             backend 28002; prod: edge listen 28014 ->
                             backend 28011)
  - backend/Dockerfile      (default/dev port 28002)
  - .env.development.example / .env.release.example

PostgreSQL and storage are compose `expose`-only services: they are reachable
only inside the compose network and are NEVER published on a host port, so the
production database is never internet-accessible.
"""

DEV_PORTS = {
    "frontend": 28001,          # Vite dev server (tenant-app), host-published for HMR
    "backend": 28002,           # uvicorn dev API, host-published for direct access
    "storage": 28003,           # storage container — expose only
    "database": 28004,          # postgres — expose only (postgres -p 28004)
    "nginx": 28005,             # dev edge gateway, host-published (ngrok target)
    "ngrok": 28006,             # ngrok dashboard host port (container 4040)
    "cloudflared": 80,          # host-network tunnel (production only, not dev)
}

PROD_PORTS = {
    "backend": 28011,           # uvicorn release API — expose only
    "storage": 28012,           # storage container — expose only
    "database": 28013,          # postgres — expose only (postgres -p 28013)
    "nginx": 28014,             # edge nginx (api/app hosts), host-published
    "ngrok": 28015,             # reserved (unused; prod uses cloudflared on 80)
    "cloudflared": 80,          # host-network tunnel -> 127.0.0.1:28014
}

# Mapping of ports.env keys -> (env, role). deploy.py renders deploy/ports.env
# from DEV_PORTS/PROD_PORTS so bash scripts (deploy-release.sh, self-pull.sh)
# and compose env files always match the registry above.
PORT_ENV_KEYS = [
    # (key, env, role)
    ("FRONTEND_DEV_PORT", "dev", "frontend"),
    ("BACKEND_DEV_PORT", "dev", "backend"),
    ("STORAGE_DEV_PORT", "dev", "storage"),
    ("DATABASE_DEV_PORT", "dev", "database"),
    ("NGINX_DEV_PORT", "dev", "nginx"),
    ("NGROK_DASHBOARD_PORT", "dev", "ngrok"),
    ("BACKEND_RELEASE_PORT", "prod", "backend"),
    ("STORAGE_RELEASE_PORT", "prod", "storage"),
    ("DATABASE_RELEASE_PORT", "prod", "database"),
    ("NGINX_RELEASE_PORT", "prod", "nginx"),
    ("NGROK_RELEASE_PORT", "prod", "ngrok"),
]


def ports_env_lines() -> str:
    """Render the bash-compatible deploy/ports.env file content."""
    lines = ["# Generated from deploy/ports.py - do not edit by hand.",
             "# Single source of truth: DEV_PORTS / PROD_PORTS in deploy/ports.py."]
    for key, env, role in PORT_ENV_KEYS:
        table = DEV_PORTS if env == "dev" else PROD_PORTS
        lines.append(f"{key}={table[role]}")
    return "\n".join(lines) + "\n"


def port(env: str, role: str) -> int:
    """Look up a canonical port by environment ('dev'|'prod') and role."""
    table = DEV_PORTS if env == "dev" else PROD_PORTS
    return table[role]