worker_processes auto;

events {
    worker_connections 4096;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 100M;

    server {
        listen 8080;
        server_name api.vijaykrsha.online;

        include /etc/nginx/routes/*.conf;

        location = /health {
            access_log off;
            return 200 "VEGA Gateway OK\n";
            add_header Content-Type text/plain;
        }

        location / {
            return 404;
        }
    }
}
