events {
    worker_connections 1024;
}

http {
    # Add this line to allow uploads up to 20 Megabytes
    client_max_body_size 20M; 

    map $http_x_forwarded_proto $forwarded_proto {
        default $http_x_forwarded_proto;
        "" $scheme;
    }

    server {
        listen 80;
        server_name localhost;

        # Force trailing slash so the base href works perfectly
        location = /rent {
            return 301 /rent/;
        }

        # Route 1: The Rent App (Port 20081)
        location /rent/ {
            proxy_pass http://rent_app:20081/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $forwarded_proto;
            
            # This ensures FastAPI gets the correct path headers
            proxy_set_header X-Forwarded-Prefix /rent;
        }
    }
}
